version: '3.8'
x-environment:
  &default-environment
  MYSQL_ROOT_PASSWORD: yourpassword
  MYSQL_DATABASE: yourdatabase
  MYSQL_USER: youruser
  MYSQL_PASSWORD: yourpassword

services:
  back: # Go
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *default-environment
    depends_on:
      - mysql
    networks:
      - app-network

  front: # Vue
    build: web/front
    networks:
      - app-network

  mysql:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      <<: *default-environment
    networks:
      - app-network

  # Прокси-сервер. Он вынесен в отдельный контейнер, чтобы обеспечить
  # независимость и изолированность сервисов. Это упрощает масштабирование и обновление
  # каждого сервиса независимо друг от друга.
  proxy: # Nginx
    build: ./web/proxy
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - front
      - back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge