version: '3.8'
x-environment:
  &default-environment
  REDIS_PASSWORD: yourpassword
  REDIS_PORT: 6379
  REDIS_DATABASES: 1

services:
  back: # Go
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *default-environment
    depends_on:
      - redis
    networks:
      - app-network

  front: # Vue
    build: web/front
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --requirepass yourpassword
    environment:
      <<: *default-environment
    networks:
      - app-network

  # Прокси-сервер. Он вынесен в отдельный контейнер, чтобы обеспечить
  # независимость и изолированность сервисов. Это упрощает масштабирование и обновление
  # каждого сервиса независимо друг от друга.
  proxy: # Nginx
    build: ./web/proxy
    ports:
      - "8080:80"
    depends_on:
      - front
      - back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
